name: example
description: Example for flutter_translate_gen

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_translate_annotations: ^1.0.1
  flutter_translate_gen:
    path: ../
  build: '>=1.2.1 <=1.2.2'
  build_runner: '>=1.7.0 <=1.7.2'
