name: flutter_translate_gen
description: Statically-typed localization keys generator for flutter_translate.
version: 1.0.0
author: Jesway <hello@jesway.com>
homepage: https://github.com/jesway/flutter_translate_gen

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dart_casing: ^1.0.0
  dart_utils: ^1.0.1
  source_gen: ^0.9.4+6
  build: ^1.2.1
  code_builder: ^3.2.0
  analyzer: ^0.38.5
  glob: ^1.2.0
  flutter_translate_annotations: ^1.0.0

dev_dependencies:
  build_runner: ^1.7.0
