name: flutter_translate_gen
description: Statically-typed localization keys generator for flutter_translate.
version: 2.2.0
homepage: https://jesway.com
repository: https://github.com/Jesway/Flutter-Translate-Gen

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  analyzer: ^5.13.0
  async: ^2.11.0
  build: ^2.4.0
  code_builder: ^4.5.0
  dart_casing: ^2.0.0
  dart_style: ^2.3.0
  dart_utils: ^2.0.0
  flutter_translate_annotations: ^2.1.0
  glob: ^2.1.0
  source_gen: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.0